<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MailKit" Version="4.13.0" />
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.7" />
        <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.7" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Auxilia.Messaging\Auxilia.Messaging.csproj" />
        <ProjectReference Include="..\..\Auxilia.PlatformData\Auxilia.PlatformData.csproj" />
        <ProjectReference Include="..\..\Auxilia.Workflows\Auxilia.Workflows.csproj" />
        <ProjectReference Include="..\..\Auxilia.Core.Client\Auxilia.Core.Client.csproj" />
        <ProjectReference Include="..\..\Auxilia.Core.Contracts\Auxilia.Core.Contracts.csproj" />
    </ItemGroup>

    <ItemGroup>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
            <_Parameter1>Auxilia.Adapters.Email.Tests</_Parameter1>
        </AssemblyAttribute>
    </ItemGroup>

</Project>
